name: github_explorer_starter
description: "Starter app for the Flutter senior developer take-home assignment."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.6

  # Uncomment whichever state management approach you choose to use
  # flutter_bloc: ^8.1.5
  # flutter_riverpod: ^2.5.1

  # Uncomment whichever persistence approach you choose to use
  # sqflite: ^2.3.3
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0

  # Uncomment whichever router you choose to use
  # go_router: ^14.2.0
  # auto_route: ^8.1.2

  # Needed if you implement the "share" native integration option
  # share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
