name: github_explorer_starter
description: "Starter app for the Flutter senior developer take-home assignment."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.11.1
  flutter_riverpod: ^3.4.3
  go_router: ^18.0.2
  clock: ^1.1.3
  flutter_secure_storage: ^11.2.0
  dart_jsonwebtoken: ^3.4.1
  sqflite: ^2.4.4+1
  path: ^1.9.1
  share_plus: ^13.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  fake_async: ^1.3.3
  sqflite_common_ffi: ^2.4.3

flutter:
  uses-material-design: true
